### PR TITLE
Add context manager support.

### PR DESCRIPTION
**Pull request by brmmm3**

### CODE REVIEW

**Comment by benhoyt** [comment]
Hi @brmmm3, thanks for this. I notice the tests are failing for Python 2.7 due to missing "yield from" syntax (should be straight-forward to replace with a for loop and "yield"), as well as in Python 3.x due to missing context manager support in the Python version of scandir. I also think we need to add tests specifically for the context manager support.

I'm curious, did you pull this code from the CPython 3.x repo and backport it, or did you start from scratch?

**Comment by brmmm3** [comment]
Oh I've only test it with Python 3.7. Ok then the code needs some rewrite.
I've taken the code from the latest Python git repo.

**Comment by brmmm3** [comment]
I've fixed the incompatibilites with older Python versions. But appveyor is still failing, which I don't understand...

**Comment by benhoyt** [comment]
I think it's failing because the "generic" and Python versions of scandir are missing the with statement support (though I don't know why the Linux version is succeeding - that's weird.

**Comment by benhoyt** [comment]
Doing some cleanup, and closing this due to lack of interest. Feel free to reopen if you want to address the issue with the generic and Python versions lacking support, as well as adding tests.

**Pull request closed without merging**
