### PR TITLE
compatibility with PyPy as well as Python < 3.3

### PR DESCRIPTION
**Pull request by aarzee**
This includes the changes recommended by @benhoyt in #51.

### CODE REVIEW

**Comment by aarzee** [comment]
Note that I don't have any CPython 3 environments to test this with, as I'm having a separate issue with virtualenv making an environment (pypa/virtualenv#779). This currently successfully installs with `python2.6`, `python2.7`, `pypy` and `pypy3` environments.

**Comment by aarzee** [comment]
Pinging @benhoyt, don't mean to be impatient but was wondering if/when this will be looked at.

**Comment by benhoyt** [comment]
Unfortunately I can't give a timeframe. I was hoping in the last few weeks, but haven't even had a chance for smaller blocks of time on personal projects. It looks good at a glance, but I need to test in a few more environments.

**Comment by aarzee** [comment]
Is there anyone else who could look at it?

**Comment by benhoyt** [comment]
Fixed in version 1.2 (though note that there's still a fairly major issue with `DirEntry.stat()` on PyPy -- see more at https://github.com/benhoyt/scandir/issues/51#issuecomment-168447895).

**Pull request closed without merging**
